version: "3.8"
services:
  db:
    image: mysql
    container_name: am_database
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - assetmanagement

  phpmyadmin:
    image: phpmyadmin
    container_name: am_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - assetmanagement

  www:
    build: docker/php
    container_name: am_www
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - assetmanagement

networks:
  assetmanagement:

volumes:
  db-data:
